### ISSUE TITLE
not able to access lookout-for-metric service

### ISSUE THREAD

**Issue by Jaeyo** [aws-samples/amazon-lookout-for-metrics-samples#11]
I know it's not a good idea to post it here, but I've been unable to find a solution for a WEEK. excuse me please.

I requested an access to lookout for metric last week. and I received an approval mail a weeks ago. (2020-12-21 19:54:00 UTC)

some of content of approval mail is as below:
"Your request for the Amazon Lookout for Metric preview has been approved! Your AWS Account ID has been approved and you should have access to the service within 2 business days."

but I couldn't access to the service "lookout for metric" on aws console. 
when i clicked link to "lookout for metric" service, then I always redirected to "https://aws.amazon.com/ko/lookout-for-metrics/  " which is just general service introduction page.
I tried all supported regions (tokyo, n. virginia, ohio, oregon, ireland) but nothing works.
clearing cookie or using secret mode on chrome also didn't works.

to solve this problem, I've created an issue at aws support center even twice. (case id 7770236061, 7780979771)
but they couldn't help me. they just said that wait for 2 business day, clear the cookies / cache, use another browser / os / computer. nothing works.

I just want to know, did I get the correct approval? or do I have to wait a little longer?
do I have to request the preview again which I already requested twice?

my business email is `lee.jaeyong@sk.com`. please check it out for me, or just let me know where can i get support. (except support center, cause they haven't solved my case twice.)

thanks.

@chrisking @shimomut

**Comment by shimomut** [comment]
@Jaeyo, thank you for reaching out to us, and sorry for the trouble. Checking the support cases you created and your Preview approval status. Will get back here.

**Comment by chrisking** [comment]
@Jaeyo, @shimomut escalated this internally, will be reaching out through your email now.

**Comment by chrisking** [comment]
Also for others attempting to find the service later, the URL is https://console.aws.amazon.com/lookoutmetrics/home?region=us-east-1#landing but it depends on you having preview access.

**Comment by chrisking** [comment]
Closing due to issue being resolved out of band from repository.
