### ISSUE TITLE
Using AggregationFunction "AVG" for "views" metrics, but should use SUM

### ISSUE THREAD

**Issue by shimomut** [aws-samples/amazon-lookout-for-metrics-samples#13]
In the getting_started notebooks, AggregationFunction "AVG" is used for "views" metrics, but should use SUM.

**Comment by chrisking** [comment]
Will fix in the current workshop refactor I'm doing now. Thanks for the heads up!

**Comment by shimomut** [comment]
Thanks. We should fix 2 notebooks "3.GettingStartedWithLiveData.ipynb" and "4.BacktestingWithHistoricalData.ipynb".

**Comment by chrisking** [comment]
Correct, though I will be swapping their order (3 becomes 4)
