### ISSUE TITLE
Use of "!pip" may be environment dependent

### ISSUE THREAD

**Issue by shimomut** [aws-samples/amazon-lookout-for-metrics-samples#16]
We are using "!pip" to uninstall/install SDK packages, but this may be environment dependent. When there are multiple versions of python installations on the environment, the pip executable "!pip" finds depending on the order of environment variable PATH, and it doesn't necessarily find the one for Jupyter kernel.

We should consider other options.

option1 - use "%pip" instead of "!pip"
option2 - !{sys.executable} -m pip install [package_name]

I haven't finalized my investigation, so not sure which option is better. Tracking the investigation and discussion here.

**Comment by shimomut** [comment]
Reading this article:

https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

**Comment by shimomut** [comment]
%pip magic command has been introduced since 2018-Dec.

https://github.com/ipython/ipython/issues/11481

**Comment by chrisking** [comment]
Ok let's go with that and then work it into the Forecast and Personalize pages if needed ( probably not needed )

**Comment by shimomut** [comment]
I will confirm that %pip magic command on some environments, and will create a pull request.

**Comment by shimomut** [comment]
Thank you for reviewing and merging the pull-request - https://github.com/aws-samples/amazon-lookout-for-metrics-samples/pull/17
Closing this issue.
