### ISSUE TITLE
"!wget" and "!mv" don't work on Windows environment

### ISSUE THREAD

**Issue by shimomut** [aws-samples/amazon-lookout-for-metrics-samples#18]
We are using "!wget" and "!mv" to download and rename SDK package, but these commands don't work on Windows environment.

**Comment by chrisking** [comment]
There's not really a Windows replacement outside of the Linux subsystem. These are only used for the beta components, tempted to leave them as is and deprecate post GA. Thoughts? Also, it might work for us just to say these examples are to guide you in the happy path through SageMaker but may require edits for alternative configurations. Thoughts?

**Comment by shimomut** [comment]
I am fine if we are aware of this environment dependency and this is tentative issue until GA. For long term, we should try to keep notebooks environment independent by using python's standard library.

example)
wget -> define utility.wget() in utility.py
mv -> use os.rename()

**Comment by chrisking** [comment]
Closing as we killed those notebooks.
