### ISSUE TITLE
How can this service differ from cloudwatch anomaly detection?

### ISSUE THREAD

**Issue by Jaeyo** [aws-samples/amazon-lookout-for-metrics-samples#20]
I'd like to apply anomaly detection to my service, but I'm confused about which service to use.
Since the services are still in early stages, I haven't been able to get enough information from web.
I'd like to ask a few questions to determine which service is appropriate.

- Are you using a different approach than CloudWatch to detect anomalous?
- Are you targeting dataset with different characteristics? (i.e. system metric -> cloudwatch anomaly detection, business metric -> lookout for metric)

In addition to above questions, I would appreciate if you could provide enough information to distinguish use cases from CloudWatch anomaly detection.

Thanks for your great work.

**Comment by chrisking** [comment]
Thanks for reaching out! 

Regarding the approaches, we use a host of different statistical and ML models to determine the most performant for anomaly detection on your data. This is different than CW which uses just one ML also. 

As far as dataset characteristics, I've seen customers be successful with both system metric and business metric data with Lookout for Metrics. If CW AD is working well enough, and your data is already in CW it can be a great solution. A number of customers have reported a lower false positive rate with Lookout for Metrics, especially after using the labeling feature when anomalies are found. Also Lookout for Metrics can provide relevant aggregation of events to showcase the scope of an anomaly moreso than you get with CW AD.

Let me know if you need anything else!

**Comment by Jaeyo** [comment]
Thanks for thoughtful answer. Your great work would help me a lot.
