### ISSUE TITLE
Wrong variable referenced for role ARN in alert creation step

### ISSUE THREAD

**Issue by ylukin** [aws-samples/amazon-lookout-for-metrics-samples#23]
The fourth notebook is referencing the wrong variable in the anomaly alert creation step:

`response = L4M.create_alert(
    Action = {
      "SNSConfiguration": { 
         "RoleArn": sns_role_arn,
         "SnsTopicArn": topic_arn
      }`

It should be:
`response = L4M.create_alert(
    Action = {
      "SNSConfiguration": { 
         "RoleArn": role_arn,
         "SnsTopicArn": topic_arn
      }`

**Comment by chrisking** [comment]
corrected in 51d295bc4af3d044195852f5ef0230e6e4202276

**Comment by chrisking** [comment]
Closing due to the above commit being in main.
