### ISSUE TITLE
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'

### ISSUE THREAD

**Issue by timwukp** [aws-samples/amazon-lookout-for-metrics-samples#27]
in notebook 4.ExportingAnomalies,

there has an error in 'Building the Dataframe'
'

**Comment by chrisking** [comment]
I found this: https://stackoverflow.com/questions/60266554/type-object-datetime-datetime-has-no-attribute-fromisoformat can you confirm you are using Python > 3.7?
